### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ge9** [fangfufu/httpdirfs#105]
I'm very interested in this software, and hope for Windows support.
I found you mentioned that you may implement this using WinFSP.
https://www.reddit.com/r/opendirectories/comments/da8lmp/would_anyone_be_interested_in_porting_httpdirfs/
I've used some other file systems for Windows using WinFSP (ex. SSHFS-Win), and they works well (sometimes we must specify `idmap=user`, `gid=0` or `umask=000` to avoid permission problem).
(When) will this happen?

**Comment by fangfufu** [comment]
I don't really have any motivation to develop this for Windows, hence I made the post. If anyone wants to port this to Windows. I am more than happy to help.
