### ISSUE TITLE
Support for h5ai(HTML5 Apache Index) directory listing

### ISSUE THREAD

**Issue by mahfuzullah** [fangfufu/httpdirfs#107]
h5ai (https://github.com/lrsjng/h5ai) is a file indexer/directory listing that is intended as a update of Apache DirectoryIndex, you can use it to read pdf/play mp3 on browser, etc etc.

a directory that i regularly mount using httpdirfs just updated to h5ai, but unfortunately httpdirfs does not support h5ai yet...

**Comment by mahfuzullah** [comment]
the main difference between h5ai and Apache directory listing is instead of "/.." h5 uses "parent directory" which causes some sort of parsing error.

here's a demo site for replicating this behavior https://larsjung.de/h5ai/demo/

![image](https://user-images.githubusercontent.com/7601631/196777145-d7aea962-f3ca-4893-b943-b7fef91101bb.png)

**Comment by fangfufu** [comment]
Oh what you described is not a problem. The actual problem is that with h5ai, all the links start with ``/``, HTTPDirFS assumes that no link starts with '/', and it uses the ``href`` attribute as the filename, rather than the text associated wit the ``a`` tag.

**Comment by chrysn** [comment]
With the introduction of `make_link_relative` in https://github.com/fangfufu/httpdirfs/pull/121, this should work now.

**Comment by fangfufu** [comment]
Closing this for now, feel free to reopen it.
