### ISSUE TITLE
Create a Debian package for it

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/httpdirfs#11]
Debian is the only OS I use, you know...

https://mentors.debian.net/
https://github.com/phusion/debian-packaging-for-the-modern-developer
https://www.debian.org/doc/manuals/maint-guide/

**Comment by jcharaoui** [comment]
I can help review/upload the package, I'm a Debian Developper!

**Comment by fangfufu** [comment]
@jcharaoui , on that's great! I will package it when I next have time - I am a bit busy right now.

**Comment by jcharaoui** [comment]
@fangfufu Debian will soon enter its next freeze so if we want httpdirfs to enter the next stable release we should hurry! Are you still interested in packaging it?

**Comment by fangfufu** [comment]
@jcharaoui , I am busy with school work right now, if you want to package it, feel free to do so. I am happy to provide help and etc.

**Comment by jcharaoui** [comment]
I've created an ITP (Intent to package) report here : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918961

**Comment by fangfufu** [comment]
Is there anything that I need to do?

**Comment by jcharaoui** [comment]
No, I was just keeping you up to date on the process. Sorry for the noise.

I'll let you know what I have a package you can test :)

**Comment by fangfufu** [comment]
Feel free to submit a pull request for all the Debian packaging control files. I might just end up giving you write access to the repository. :)

**Comment by fangfufu** [comment]
The freeze policy is here. We don't have much time left. Please let me know if there is more I can do. 
https://release.debian.org/buster/freeze_policy.html

**Comment by jcharaoui** [comment]
@fangfufu I've sent over a few pull requests. These should take care of a few packaging warnings. There's also the issue of creating a manpage, but I have to check if I can generate that from `--help` using `help2man`.

As I side note I would like to suggest following semantic versioning for future releases as defined here: https://semver.org/

**Comment by jcharaoui** [comment]
Yes, 1.0.1 sounds good. If you could tag it a create a release on GitHub, that makes it easier on the packaging side as well.

**Comment by fangfufu** [comment]
I am happy to tag it. Do you plan to submit any more patches?

**Comment by jcharaoui** [comment]
Not currently, but I'm not done with the packaging work. I should be able to complete it by the end of the week. I don't mind if you wait before tagging a new release.

**Comment by fangfufu** [comment]
I think I will tag it after you submitted all patches. :)

**Comment by fangfufu** [comment]
I have invited you as a collaborator. Feel free to accept the invite, and commit directly to the repository. :)

**Comment by jcharaoui** [comment]
Alright I think I'm done with patching. The project looks in good shape, if you agree let's bump the version to 1.0.1 and I can upload that to Debian. The package is ready to go.

**Comment by jcharaoui** [comment]
Nice, thanks! But you forgot to bump the version number in the Makefile :)

**Comment by fangfufu** [comment]
Right, I deleted the release and updated the Makefile. ;)

**Comment by fangfufu** [comment]
I tagged a new released with version 1.0.1, with an updated Makefile, in case you haven't noticed. :)

**Comment by jcharaoui** [comment]
I've uploaded my work to the Debian GitLab host at https://salsa.debian.org/lavamind/httpdirfs-fuse

I've also submitted my package for inclusion in the main archive. Hopefully, it will get processed in time!

**Comment by fangfufu** [comment]
Ah thank you so so much!!! I will buy you a beer if I ever meet you in real life. Could you tell me more about Debian's Gitlab presence please? (A few links would do)

**Comment by jcharaoui** [comment]
Here: https://wiki.debian.org/Salsa

> Salsa is the name of a collaborative development server for Debian based on the gitlab software. Salsa is supposed to provide the necessary tools for package maintainers, packaging teams and other Debian related individuals and groups for collaborative development.

**Comment by jcharaoui** [comment]
I'm based in Montreal, Canada. Let me know if you're in town some day, we have regular free software / Debian meetups!

**Comment by fangfufu** [comment]
By the way, do you know how long we have to wait before the package appear on in the repository? It hasn't appeared at packages.qa.debian.org yet.

**Comment by jcharaoui** [comment]
@fangfufu Unfortunately, the Debian freeze is today and the package hasn't entered the archive yet. This means that httpdirfs is very unlikely to be part of the next Debian release. However, all is not lost, because once the release is published, we can still upload a backport package for buster.

**Comment by fangfufu** [comment]
@jcharaoui , oh well. Thanks for all your effort though. :+1:
