### ISSUE TITLE
LinkTable_print(): Invalid link count: 0, h

### ISSUE THREAD

**Issue by kaustubhk24** [fangfufu/httpdirfs#110]
root@dm-$  httpdirfs -f  http://103.xx.xxx.xx/Data/ test
--------------------------------------------
 LinkTable 0x55c7082c4620 for http://103.xx.xxx.xx/Data/
--------------------------------------------
0 H 0  http://103.xx.xxx.xx/Data/
1 D 0 3D http://103.xx.xxx.xx/Data/3D
2 D 0 Games http://103.xx.xxx.xx/Data/Games
3 D 0 Hindi http://103.xx.xxx.xx/Data/Hindi
4 D 0 Movies http://103.xx.xxx.xx/Data/Movies
5 D 0 Software http://103.xx.xxx.xx/Data/Software
6 D 0 TV Series http://103.xx.xxx.xx/Data/TV%20Series
7 D 0 lost+found http://103.xx.xxx.xx/Data/lost%2Bfound
8 D 0 movies1 http://103.xx.xxx.xx/Data/movies1
9 D 0 t http://103.xx.xxx.xx/Data/t
10 D 0 tvseries http://103.xx.xxx.xx/Data/tvseries
--------------------------------------------
LinkTable_print(): Invalid link count: 0, h

I'm getting this error

**Comment by fangfufu** [comment]
You are not providing enough information, and you are not providing me access to your server for debugging purposes.
