### ISSUE TITLE
How to cleanly clear cache

### ISSUE THREAD

**Issue by maysara** [fangfufu/httpdirfs#111]
Greetings, I'm using the cache function and I understand it is permanent, but I need to clear it as it got too big, restarting is not clearing it. what is the cleanest way to clear it? I have around 1300 mounted directories, so what should I do? turn the mount off and delete the path content?

**Comment by fangfufu** [comment]
it is in your ``~/.cache/httpdirfs``.

**Comment by fangfufu** [comment]
I probably should add an option to clear the cache.

**Comment by maysara** [comment]
I'm currently unmounting everything and deleting the folders content when I run out of cache disk space, I'm specifying a path for each mount separately, but as I'm not sure if I could keep meta and delete data for example.

What I wonder is where the line should be drawn between when to use httpdirfs cache and deploying an http cache server (nginx/varnish/squid/nuster) instead.

In my particular case, I would not mind keeping the files as long as I'm not running out of space, since I eventually will, finely controlling what to keep and how long ..etc might be better controlled by a proxy cache server, but what are the things that would make httpdirfs work faster/better in this constellation? should I just drop httpdirfs cache and rely on the http cache? is there a point in keeping both? what is internally gained/saved when accessing files from the httpdirfs cache vs. a local proxy cache?

**Comment by fangfufu** [comment]
@maysara , sorry for the late reply. I missed that you replied to the thread again. 

I would say you should try benchmarking yourself. It depends on which proxy server you use. I don't know how proxy server cache partially downloaded files. The exact details is also implementation dependent. 

What is certain is that proxy server probably won't cache HTTPS contents, whereas this filesystem definitely will. ?

I hope these help.

**Comment by fangfufu** [comment]
Done via 194a10f
