### ISSUE TITLE
Unable to install on Linux

### ISSUE THREAD

**Issue by Babyyoda777** [fangfufu/httpdirfs#118]
Hi,
I cloned the repo and ran g make which worked successfully. Unfortunately when I then ran sudo gmake install it gives me an error:

`    /usr/local/bin/httpdirfs
install -m 644 -D doc/man/httpdirfs.1 \
        /usr/local/share/man/man1/httpdirfs.1
install: cannot stat 'doc/man/httpdirfs.1': No such file or directory
gmake: *** [Makefile:39: install] Error 1`

**Comment by fangfufu** [comment]
Which distro are you on?

**Comment by fangfufu** [comment]
Closing the ticket because I haven't got a reply for a long time.
