### ISSUE TITLE
Problem with HTTP basic authentication

### ISSUE THREAD

**Issue by jcharaoui** [fangfufu/httpdirfs#13]
Hello, I'm trying to use httpdirfs with a URL protected by basic auth, but it doesn't work right. When supplying the correct credentials using `--username` and `--password`, I get these messages:

```
libcurl SSL engine: OpenSSL/1.0.2l
LinkTable_new(https://example.com/);
link.c: LinkTable_new() cannot retrive the base URL, URL: https://example.com/, HTTP 401
Error: Network initialisation failed.
```

When using a URL with the credentials embedded, eg. `https://user:pass@example.com`, then the initial connection is established correctly but I can't browse to any subfolders:

```
libcurl SSL engine: OpenSSL/1.0.2l
LinkTable_new(https://user:pass@example.com/);
LinkTable_new(https://user:pass@example.com/foo);
link.c: LinkTable_new() cannot retrive the base URL, URL: https://user:pass@example.com/foo, HTTP 401
```

This is on a Debian stretch system.

Thank you for this useful piece of software!

**Comment by fangfufu** [comment]
How did you set up your HTTP authentication? Which server did you use? 

I only tested the HTTP authentication stuff with the following set up: 

With this password file, 
    test:$apr1$HTcy1Trp$hqjVOxq2DP7bov6lOD/Kt0

And this ``.htaccess`` file
    AuthType Basic
    AuthName "Password Protected Area"
    AuthUserFile /home/fangfufu/public_html/password
    Require valid-user

**Comment by fangfufu** [comment]
Scratch my above comment - I think there is something wrong with the configuration file parser. I am looking into it now.

**Comment by fangfufu** [comment]
Could you disable the configuration file for now, please?

**Comment by jcharaoui** [comment]
@fangfufu I wasn't using a configuration file, just the command-line parameters. I tried to reproduce this problem with other URLs, but wasn't able to, so it might be something specific with the server I'm trying to connect to, but not sure what. I contacted the administrator to see if I can obtain the Apache configs.

**Comment by fangfufu** [comment]
Does the username / password have some special character or something? It is important to know what kind of authentication scheme that server uses.

**Comment by fangfufu** [comment]
I patched the config file parser anyway, please download the new version and have a look. However I suspect the your problem is unrelated anyway.

**Comment by fangfufu** [comment]
In that case, I really need to know the authentication scheme of that web server.

**Comment by fangfufu** [comment]
I can't really tell by the look of it, it is similar to mine. HTTP 401 indicates authentication error. Could I possibly have access to a server that is similar to that one?

**Comment by fangfufu** [comment]
Closing ticket as there hasn't been further updates in the last week - feel free to reopen it.

**Comment by jcharaoui** [comment]
Sorry, yes I can send you the URL by email. Does that work?

**Comment by jcharaoui** [comment]
@fangfufu I was able to obtain an server-side access log entry capture when the problem occurred. The problem appeared very clearly: the username and password sent to the auth mechanism are inverted! After swapping around the values for `--username` and `--password`, it worked.

**Comment by fangfufu** [comment]
Brilliant, I am glad that it is now resolved! :+1:

**Comment by fangfufu** [comment]
@jcharaoui , apparently I had been working on the dev branch, for the patch related to the config file. I have merged that back to the master branch, alongside your pull request. I have tagged a release version based on that.
