### ISSUE TITLE
Cache mode doesn't work with escaped URL. 

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/httpdirfs#138]
Cache mode does not appear to work with escaped URL. This issue has appeared twice. The first time here: https://github.com/fangfufu/httpdirfs/issues/127
> Found this URL with : in it that is apparently valid. Just logging it incase anyone tries the same thing. suse should probably be replacing : with %3A on there end. Httpdirfs seams to not be able to read theses links, likely similar to the spaces issue for %20 in urls.

The second time it appeared here: https://github.com/fangfufu/httpdirfs/issues/86#issuecomment-2041147955_
> Please, how to mount the file with url containing spaces? when I mounted in escaped format, the file name is escaped too and cannot be opened in OS. When I provide URL non excaped, it does not mount (Error:src/network.c:163:curl_process_msgs: 3 - URL using bad/illegal format or missing URL)

The third time it appeared is here: https://github.com/fangfufu/httpdirfs/issues/128
> Single file mode breaks when cache is enabled and URL has percent-encoding

Another appearance associated with single-file mode is here: https://github.com/fangfufu/httpdirfs/issues/99#issuecomment-1305492276

**Comment by fangfufu** [comment]
Some initial investigation results: 
https://github.com/fangfufu/httpdirfs/pull/123/files#r1587024220

**Comment by fangfufu** [comment]
This is related to:
https://github.com/fangfufu/httpdirfs/issues/128

**Comment by fangfufu** [comment]
The root cause of the problem is labelled in this commit: https://github.com/fangfufu/httpdirfs/commit/3e7d9f0294bc3d5d1e2ccfea6b3b6047ddd1288c

I still need to resolve this.

**Comment by fangfufu** [comment]
Potentially fixed via 28293b5ccdc4f65e5721ba2fe978f1cff066d0d7. Needs more testing.

**Comment by fangfufu** [comment]
@WizzardSK, I think the issue had been resolved, please come and have a look.

**Comment by fangfufu** [comment]
The issue is not resolved for single-file-mode.

**Comment by fangfufu** [comment]
Duplicated here: 
https://github.com/fangfufu/httpdirfs/issues/99

**Comment by WizzardSK** [comment]
well, the problem was only in single-file mode

**Comment by fangfufu** [comment]
Fixed via 2fa2bb9cf068221b0fb625e600af8fe33f181214. Feel free to re-open the ticket if it doesn't work for you.
