### ISSUE TITLE
Fix CodeQL

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/httpdirfs#144]
CodeQL is reporting these errors:
```
  ./configure: line 3493: syntax error near unexpected token `-Wunused-command-line-argument,NUCLA=-Wno-unused-command-line-argument,-Werror'
  ./configure: line 3493: `AX_CHECK_COMPILE_FLAG(-Wunused-command-line-argument,NUCLA=-Wno-unused-command-line-argument,-Werror)'
  make: *** [Makefile:364: config.status] Error 2
```

I have no idea what might be causing this. The failure seems to be intermittent too.

**Comment by fangfufu** [comment]
@jikamens , I don't know if you fancy having a look at this.

**Comment by fangfufu** [comment]
Update: To facilitate the investigation, I have installed a kubuntu virtual machine - I think the GitHub runners are on Ubuntu.

**Comment by jikamens** [comment]
I can't reproduce this locally. Can you link to an action run that had this problem so I can look at the run log and see if I can learn anything from it?

**Comment by fangfufu** [comment]
Here:
https://github.com/fangfufu/httpdirfs/actions/runs/9044999577/job/24854267368

It is very intermittent.

**Comment by jikamens** [comment]
Will look as time permits, not sure when that will be.

**Comment by fangfufu** [comment]
No worries. It might be GitHub infrastructure problem.

**Comment by jikamens** [comment]
This is probably the same issue as #153. If you add `autoconf-archive` to the dependencies for the CodeQL job it should fix it.

**Comment by fangfufu** [comment]
Thanks. I think this is fixed.
