### ISSUE TITLE
What is the correct way of temporarily adding ``-DDEBUG`` into the compilation command?

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/httpdirfs#151]
@jikamens , what is the correct way of temporarily adding ``-DDEBUG`` temporarily into the compilation command? Is it possible to specify something when you do ``./configure``?

**Comment by jikamens** [comment]
You can do `configure CPPFLAGS=-DDEBUG`.

**Comment by fangfufu** [comment]
Thanks! :)
