### ISSUE TITLE
[Feature] Add custom HTTP headers

### ISSUE THREAD

**Issue by redindian** [fangfufu/httpdirfs#157]
It would be great to be able to add additional custom headers like `Accept`. The file I'm trying to mount requires this header. But being able to add any headers would be even better!

Found an example in the documentation:
https://curl.se/libcurl/c/CURLOPT_HTTPHEADER.html

Rclone uses the `--http-headers` option for this:
https://rclone.org/http/#http-headers

Seems to be doable since most of the setup is already done here:
https://github.com/fangfufu/httpdirfs/blob/master/src/link.c#L101

Don't have experience with C unfortunately, so I could give it a try but it will probably take me a lot more time. Let me know if you like this request and would be able to add it. Otherwise I'll try and give it a go. No promises. 😄

**Comment by fangfufu** [comment]
If you write a patch, I can review it. I don't promise it will be merged in though. It depends on your code quality.

**Comment by redindian** [comment]
I've opened a PR that adds this feature: https://github.com/fangfufu/httpdirfs/pull/158 

Kept it as simple as possible. One thing missing is the freeing of the `curl_slist` stored in `CONFIG.http_headers`. I wasn't sure where to do that. Guess it gets freed when the program ends also.

BTW. using the `--http-header` I was also able to overwrite the `user-agent` header.

**Comment by redindian** [comment]
I also tried running `indent -kr -nut *.c *.h` as stated in the [README](https://github.com/fangfufu/httpdirfs/blob/master/src/README.md).md, but then a lot more code is changed so I had to revert that.

**Comment by fangfufu** [comment]
Thank you very much, I have cherry-picked this commit in the master branch via 2ab8cb5035367381abfc9383ebec72fe1d94618b

**Comment by fangfufu** [comment]
> Don't have experience with C unfortunately, so I could give it a try but it will probably take me a lot more time. Let me know if you like this request and would be able to add it. Otherwise I'll try and give it a go. No promises. 😄

Btw I assume this actually works for you - I don't have any kind of CI setup, because I started this project during my PhD years, and I didn't know what CI meant!

**Comment by redindian** [comment]
Bit of a late reaction but I was kind of busy. :-) Thanks for merging, yes it works sending custom headers like this.
