### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [fangfufu/httpdirfs#2]
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [url_append](https://github.com/fangfufu/httpdirfs/blob/be06db5fe4cecd14c4e937e110e8f3755bc17b67/network.c#L81)
- [strndup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strndup.html "Duplicate a specific number of bytes from a string") ⇒ [path_to_Link](https://github.com/fangfufu/httpdirfs/blob/be06db5fe4cecd14c4e937e110e8f3755bc17b67/network.c#L416)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by fangfufu** [comment]
Well, if there is nothing I can do for the error, then I might as well ignore it. It is too much effort for this non-security-critical program.

**Comment by elfring** [comment]
I suggest to care more for [secure programming concerns](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") so that a more robust file system implementation could be achieved.

**Comment by fangfufu** [comment]
Thanks for the suggestion. I will have a look in the future. 
You are welcome to submit a pull request to patch it though.

**Comment by fangfufu** [comment]
@elfring , I have added the error handling code.

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "Software development with AspectC++?")?
* How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by elfring** [comment]
[The error detection and exception handling is still incomplete](https://github.com/fangfufu/httpdirfs/blob/5a50842440331396f6641c4e464dcc2912156e9d/network.c#L207 "Update candidate: network_init()").

**Comment by fangfufu** [comment]
It would b great if you can help me to solve the thread safety problem associated with using FUSE and curl multi interface. Running multithreaded FUSE interferes with libcurl.

**Comment by fangfufu** [comment]
How about now? What would you do if it was aspect oriented programming?

**Comment by elfring** [comment]
* How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* Aspect-oriented programming could help to [care for cross-cutting concerns](https://en.wikipedia.org/wiki/Cross-cutting_concern#Examples "Description for cross-cutting concerns") like exception handling in a safer way, couldn't it?
* Would you like to continue any software development with C++ class libraries?

**Comment by fangfufu** [comment]
I am interested in software development with C++ class libraries, yeh. I don't know which projects to contribute to though.

**Comment by elfring** [comment]
Which classes would you need for the safer development of the discussed file system implementation?

**Comment by fangfufu** [comment]
Not entirely sure.

**Comment by elfring** [comment]
Are you looking for C++ wrappers of the involved function libraries?

**Comment by fangfufu** [comment]
Why would I want that? The C libraries work fine.

**Comment by elfring** [comment]
Software developers (like you) struggle with the challenge to complete the corresponding exception handling, don't they?

**Comment by fangfufu** [comment]
So who are you? What do you do for a living?

**Comment by elfring** [comment]
Several of my software development contributions are public. You might find further evolution interesting in these areas.

:crystal_ball: Extending the programming with C++ can help to reduce recurring difficulties with system properties from the C language, can't it?
