### ISSUE TITLE
Dotfile madness (don't use ${HOME}/.httpdirfs for config)

### ISSUE THREAD

**Issue by jcharaoui** [fangfufu/httpdirfs#23]
Use `${$XDG_CONFIG_HOME}` instead.

It's explained [here](https://0x46.net/thoughts/2019/02/01/dotfile-madness/).

**Comment by fangfufu** [comment]
I will deal with it later in the week. I need to finish generating the results for this research paper then submit it... 

 Feel free to fix it yourself, if you want, you have repository write access anyway. :)

**Comment by jcharaoui** [comment]
Sure, of course! Creating this issue was more of a reminder for both of us, not a pressing demand. :)

**Comment by fangfufu** [comment]
It is now fixed. I don't know if I should bump the version number, do let me know what you think.

**Comment by fangfufu** [comment]
@jcharaoui , I decided to release a new version, otherwise it could get confusing.
