### ISSUE TITLE
Seems to fail on long directory listings

### ISSUE THREAD

**Issue by fstirlitz** [fangfufu/httpdirfs#24]
```
$ httpdirfs http://www.open-std.org/jtc1/sc22/wg14/www/docs/ "$XDG_RUNTIME_DIR/mnt/wg14"
```
generates [a log file as attached](https://github.com/fangfufu/httpdirfs/files/3051267/wg14.log) (after patching to enable `CURLOPT_VERBOSE`).

**Comment by fangfufu** [comment]
Based on the log, I have a feeling that the page in question has too many files, and libcurl tries to open too many connections at once, and that cause the whole thing to fail. I am mirroring the directory in question, then I am going to put on a local server with short URL, to see what happens.

**Comment by fangfufu** [comment]
Yeh, I managed to replicate the bug. This fails. 

    fangfufu@smithsonian:~/public_html$ for i in {1..3000}; do dd if=/dev/urandom bs=$RANDOM count=1 of=$i; done
    httpdirfs http://127.0.0.1/~fangfufu/ mnt

**Comment by fangfufu** [comment]
I believe this issue is now resolved. :) 

@jcharaoui, do you want to package this version? I bumped the version up to 1.0.3, because this is a proper bug fix.
