### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by jcharaoui** [fangfufu/httpdirfs#31]
The changes between versions should be documented inside the repository in a text file, instead of being exclusively on the GitHub releases page. Guideline in terms of format can be found here: https://keepachangelog.com/en/1.1.0/

**Comment by fangfufu** [comment]
I think this is a good idea. Should I add the previous version into the change log, or just the future releases?

**Comment by jcharaoui** [comment]
Since the full changelog isn't very long, I think it would be worth it to add previous versions into it.

**Comment by fangfufu** [comment]
Ok, I will get onto it when I next have some free time, but feel free to work on it yourself as well. :-)

**Comment by fangfufu** [comment]
Done.
