### ISSUE TITLE
Reasonable cache defaults

### ISSUE THREAD

**Issue by jcharaoui** [fangfufu/httpdirfs#32]
>     --max-seg-count     The maximum number of download segments a file
>                         can have. By default it is set to 1048576. This
>                         means the maximum memory usage per file is 1MB
>                         memory. This allows caching file up to 8TB in
>                         size, assuming you are using the default segment
>                         size.

By default cache is disabled (good) but I don't think that allowing httpdirfs to allocate up to 8TB by default of disk space is reasonable. For most users that would mean caching *everything* httpdirfs comes across...

Something in the area of 100 segments (so 800MB by default) would make more sense, I  think.

**Comment by fangfufu** [comment]
I get where you are coming from. 

However, httpdirfs uses sparse allocation, if the user's filesystem supports it, then the space isn't actually allocated until the file segments are downloaded. So I don't think it matters.

However I agree that it might be an issue if the user's filesystem does not support sparse allocation. 

Do you think it is a better idea to detect whether the user's filesystem supports sparse allocation, and set a different default cache size?

**Comment by jcharaoui** [comment]
From the information on [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Allocation_and_layout_policies), it seems FAT16/32 is a major filesystem that doesn't support sparse file allocation, so I think detection should probably be implemented.

Also, I know how sparse file allocation works, but such files are not as straightforward to manage and many tools don't deal very nicely with sparse files, which is why you don't see many programs using them. For example, the backup program I use, `borgbackup` reports the allocated size and not the actual used size, which can be misleading if you need to monitor the size of your backups.

It would also probably be more useful to be able to limit download segments overall rather than per-file.

**Comment by jcharaoui** [comment]
I'm also wondering: since we're breaking up files into segments, what's the advantage of using sparse allocation? If we fully allocate each segment then wouldn't the maximum waste of space be 1 segment per file?

**Comment by fangfufu** [comment]
Okay, I will look into how to do sparse file support detection. Although I think it is unlikely many Linux users would use FAT16/32 to store the cache folder.

Using sparse allocation makes writing httpdirfs much easier. It allows me to directly translate the ``read()`` calls to FUSE to ``fseeko()`` and ``fread()`` calls to the underlying backing cache file. Without spare allocation, and without fully allocating the space, there are two schemes I can think of to implement the cache system: 
1. Create a file for each segment. This would results in a lot of cache files for big files. Implementing ``read()`` to FUSE involves ``fopen()`` and ``fread()`` instead. I felt it was not as intuitive to implement. 
2. Append new segments to the data file as they come in. This requires the metadata to store the layout of the data file. This makes seeking much more complicated. 

Finally, a lot of Bittorrent software supports sparse files, e.g. ``Transmission`` and ``Aria2``

**Comment by fangfufu** [comment]
There doesn't seem to be a clean and easy way to query the filesystem to see if it supports sparse allocation, e.g. 
https://stackoverflow.com/questions/38718864/how-to-test-if-sparse-file-is-supported
https://github.com/mafintosh/supports-sparse-files/blob/master/index.js

It is definitely possible to implement, but I am not sure if it is worth the effort. I have updated the README giving the user a link to Wikipedia. Personally I don't really think it matters, because it is unlikely for a Linux user to use a filesystem which does not support sparse allocation for their home directory. What do you think? 

With respect to reasonable cache default, I have allowed HTTPDirFS to allocate up to 1TB by default. I think it is reasonable, because this enables the end user to browse disk images. What do you think?

**Comment by fangfufu** [comment]
I think we should just leave it as it is. :-)
