### ISSUE TITLE
Default cache directory

### ISSUE THREAD

**Issue by jcharaoui** [fangfufu/httpdirfs#33]
Suggest using `--cache` as a boolean flag to enable cache at the default location of `${XDG_CACHE_HOME}/httpdirfs`, and add `--cache-location` to specify a different cache folder.

We could also implement http://bford.info/cachedir/spec.html for the cache directory.

**Comment by fangfufu** [comment]
Ok, I will look into it, but feel free to work on it yourself. :-)

**Comment by fangfufu** [comment]
Done
