### ISSUE TITLE
Segfault with partially downloaded file and changed segment size

### ISSUE THREAD

**Issue by jcharaoui** [fangfufu/httpdirfs#37]
If a remote file is partially initialized in cache (not fully downloaded) with a segment size (eg. 8 MB), and the mountpoint is reattached later with a different segment size (eg. 2 MB), trying to read the remote file again will trigger a segmentation fault.

**Comment by fangfufu** [comment]
This is fixed in ee2d3edcbfc0fd4cfa60ba24c5a46b72cfbb2e32, the user specified segment size is ignored for existing cache files.
