### ISSUE TITLE
Adding support for password protected directories?

### ISSUE THREAD

**Issue by RazeLighter777** [fangfufu/httpdirfs#4]
It seems like it would be very easy to add. Curl already has support for username and passwords. (See  [here](https://stackoverflow.com/questions/2594880/using-curl-with-a-username-and-password#2594908)) 

This would add a lot of flexibility for people who want to mount a directory securely, and would be a great addition to the project.

**Comment by fangfufu** [comment]
Have you tried the username:password@url trick yet? e.g. http://username:password@localhost
I don't understand how to use FUSE to parse arguments.

**Comment by RazeLighter777** [comment]
That will work, but perhaps it would be better if you could pass it as a command line argument like here:

`./httpdirfs -f -u username -p password $URL $YOUR_MOUNT_POINT`

This option could be easily implemented by just adding whatever the options say to the end of the url like you have it above. Wouldn't even have to mess with fuse or curl.

**Comment by RazeLighter777** [comment]
I'm working on a simple patch now.

**Comment by fangfufu** [comment]
Thanks for being so helpful! :)

**Comment by RazeLighter777** [comment]
Alright. I finished. But I want you to take a look at my branch to make sure everything's OK before I make a push request.

**Comment by fangfufu** [comment]
Mind you, I might borrow your method to set the nax HTTP connection limit. I switched to curl-multi interface. This is way faster than rclone mount.

**Comment by RazeLighter777** [comment]
Ok. Fixing a bug right now. Might take another hour or two but then it should be good.

**Comment by fangfufu** [comment]
Awesome man, I fixed all my multithreading issues. I am downloading Debian Live DVD right now to test it. But yeh, this thing is way better than rclone mount, imho.

**Comment by RazeLighter777** [comment]
Ok the bug is fixed. Tell me when you are ready for the pull request.

**Comment by fangfufu** [comment]
Yeh, send it now. Thanks!

**Comment by fangfufu** [comment]
@RazeLighter777 , I added some more comments on your pull request - please tell me that you are still following the project! :P

**Comment by fangfufu** [comment]
Superseded under issue #8 .

**Comment by fangfufu** [comment]
@RazeLighter777 , the proper support has been added.
