### ISSUE TITLE
Subsonic API: support password authentication scheme

### ISSUE THREAD

**Issue by epoupon** [fangfufu/httpdirfs#46]
Hello,

It would be great to support password authentication for servers that are using API version <= 1.12.0
Several implementations still stick to older versions, mainly to avoid storing passwords in plain texts.
Examples:
- LMS (https://github.com/epoupon/lms)
- supysonic (https://github.com/spl0k/supysonic)

You could imagine a secure fallback to plain password method if the following conditions are met:
- first attempt returned a code 30 (Incompatible Subsonic REST protocol version. Server must upgrade.)
- the URL scheme is https

**Comment by fangfufu** [comment]
This is implemented in 05776305cbd21e68e8a8e51b4831adc320209bf1, you can activate the mode using ``--sonic-insecure``. I am not a fan of automatic protocol downgrade.

**Comment by fangfufu** [comment]
By the way, to mount your LMS, you need ``--sonic-insecure`` and ``--no-range-check``.

**Comment by epoupon** [comment]
Thanks!
