### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [fangfufu/httpdirfs#5]
I suggest to reuse a higher level build system than [your current small make script](https://github.com/fangfufu/httpdirfs/blob/50b5c1ed3de75d0fcc24ae3a858736cee3eabe58/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by fangfufu** [comment]
I have used CMake before, not autotools. Considering I am only linking in 3 libraries, I don't think this is necessary.

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.12/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by elfring** [comment]
Do you need any special software build parameters for multi-threading support (for example)?

**Comment by fangfufu** [comment]
Not really no.

**Comment by elfring** [comment]
I got an other impression from the usage of the variable “`pthread_curl_lock`”.

**Comment by fangfufu** [comment]
I think libcurl links in the pthread library, that's why I don't need to link to the pthread library myself.

**Comment by elfring** [comment]
I find your conclusion questionable.

I guess that you do not need to refer to the Pthread API if you would like to keep this file system implementation only single threaded.

**Comment by fangfufu** [comment]
libcurl and libfuse spawn their own worker thread. I do not create how they do that. 

Have you even tried running this program, might I ask?

**Comment by elfring** [comment]
I did not try to run this program so far because I noticed open issues in the source code.
