### ISSUE TITLE
macOS compilation

### ISSUE THREAD

**Issue by llucps** [fangfufu/httpdirfs#51]
Hi,

Is there any chance to make httpdirfs work under macOS? If so, could you provide instructions of how to compile from the source?

Thanks.

**Comment by fangfufu** [comment]
No, sorry. I don't have access to a Mac.

**Comment by hiliev** [comment]
@llucps If you are still interested in running HTTPDirFS on macOS, I've patched it so that it builds - see [my fork](https://github.com/hiliev/httpdirfs). Using it on an M1 Mac mini running Big Sur 11.4 right now.

**Comment by fangfufu** [comment]
@hiliev, do you want to generate a pull request? I will merge it in and write you in the README. :)

**Comment by hiliev** [comment]
I would gladly do so, with the caveat that the Makefile might be a bit too specific for my system.

**Comment by fangfufu** [comment]
I will review it properly when you send a pull request, then decide. I had a look at your repository, it looks okay so far.

**Comment by fangfufu** [comment]
I had a quick look, and tested it. It compiles fine under Debian Buster. I have merged it. Thanks a lot. I will add you in the acknowledgement section. :+1:

**Comment by llucps** [comment]
Thank you very much! I can confirm that also works using [Navidrome](https://github.com/navidrome/navidrome) as a subsonic backend.

**Comment by hiliev** [comment]
Thanks for letting me know about Navidrome. Looks like a good non-JVM alternative to *sonic.

**Comment by fangfufu** [comment]
@hiliev, you forgot to add uninstall section for Darwin, I think.

**Comment by hiliev** [comment]
But who would want to uninstall it? 😃  Anyway, fixed.

**Comment by fangfufu** [comment]
Cool thanks! :)
