### ISSUE TITLE
I have a problem，fuse: mountpoint is not empty fuse: if you are sure this is safe, use the 'nonempty' mount option

### ISSUE THREAD

**Issue by 873578156** [fangfufu/httpdirfs#54]
user1@debian:~$ sudo httpdirfs --cache https://cdimage.debian.org/debian-cd/ /mnt/book
libcurl SSL engine: OpenSSL/1.1.1d
CacheSystem_init(): directory: /root/.cache/httpdirfs/https%3A%2F%2Fcdimage.debian.org%2Fdebian-cd%2F
LinkTable_new(): disk_linktbl->num: 13, linktbl->num: 13
LinkTable_invalid_reset(): 0 invalid links
LinkTable_uninitialised_fillDone!
--------------------------------------------
 LinkTable 0x20820f0 for https://cdimage.debian.org/debian-cd/
--------------------------------------------
0 H 0  https://cdimage.debian.org/debian-cd/
1 D 0 10.3.0-live https://cdimage.debian.org/debian-cd/10.3.0-live
2 D 0 10.3.0-live https://cdimage.debian.org/debian-cd/10.3.0-live
3 D 0 10.3.0 https://cdimage.debian.org/debian-cd/10.3.0
4 D 0 10.3.0 https://cdimage.debian.org/debian-cd/10.3.0
5 D 0 current-live https://cdimage.debian.org/debian-cd/current-live
6 D 0 current-live https://cdimage.debian.org/debian-cd/current-live
7 D 0 current https://cdimage.debian.org/debian-cd/current
8 D 0 current https://cdimage.debian.org/debian-cd/current
9 D 0 project https://cdimage.debian.org/debian-cd/project
10 D 0 project https://cdimage.debian.org/debian-cd/project
11 F 15353 ls-lR.gz https://cdimage.debian.org/debian-cd/ls-lR.gz
12 F 15353 ls-lR.gz https://cdimage.debian.org/debian-cd/ls-lR.gz
--------------------------------------------
LinkTable_print(): Invalid link count: 0, https://cdimage.debian.org/debian-cd/.
--------------------------------------------
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option

**Comment by fangfufu** [comment]
Please describe what your problem is.

**Comment by 873578156** [comment]
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option

**Comment by fangfufu** [comment]
Then empty the directory before mounting?
