### ISSUE TITLE
Is is possible to get flatpak package for httpdirfs?

### ISSUE THREAD

**Issue by shoukolate** [fangfufu/httpdirfs#55]
Is is possible to get flatpak package for httpdirfs? I would like to try it on SailfishOS which recently started supporting flatpaks.

**Comment by fangfufu** [comment]
Compiling this software is not *that* difficult. You need FUSE support in SailfishOS anyway. I doubt you can get FUSE in the form of a flatpak.

**Comment by shoukolate** [comment]
If you are asking if we have fuse on SailfishOS, yes we do.

**Comment by fangfufu** [comment]
What's the problem with compiling this on SailfishOS? 

I don't have SailfishOS, and I have no experience with flatpak. I am open to ideas, but I need to know why it is necessary.
