### ISSUE TITLE
[ERROR] ./httpdirfs: error while loading shared libraries: libgumbo.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by scriptzteam** [fangfufu/httpdirfs#6]
`./httpdirfs: error while loading shared libraries: libgumbo.so.1: cannot open shared object file: No such file or directory`

On ubuntu latest :)

**Comment by fangfufu** [comment]
Have you tried installing libgumbo1? I am on Debian Stretch. I have no idea what the equivalent is on Ubuntu.

**Comment by scriptzteam** [comment]
Yep i installed once again, forgot to add "sudo" xD happens and sry, all works now.

Due to non sudo the libs wasnt copied i think...
