### ISSUE TITLE
When copying files, the program will leak memory

### ISSUE THREAD

**Issue by MecryWork** [fangfufu/httpdirfs#79]
After I copied multiple files to the local desktop, I found that the memory of `httpdifs` has increased (the copy has been completed). I wonder if the memory of the copy thread has not been released successfully.

**Comment by MecryWork** [comment]
@fangfufu Hope you can see

**Comment by fangfufu** [comment]
I probably will use static analyser such as UBSAN to check for memory leak in the long term.
