### ISSUE TITLE
Add permanent caching mode support

### ISSUE THREAD

**Issue by fangfufu** [fangfufu/httpdirfs#9]
Rather than doing range request, use CURLOPT_RESUME_FROM, and save the file to the hard drive, and record which segment had been saved.

**Comment by orent** [comment]
If this was implemented as a local 9p file server rather than a FUSE filesystem, it would automatically gain the benefits of fscache (see Documentation/filesystems/caching/fscache.txt)

**Comment by fangfufu** [comment]
@orent , the idea is that once you access the file, it saves a local copy, so you can view it when you are offline.

**Comment by orent** [comment]
The kernel has a built-in generic mechanism for local caching of remote filesystems. It is supported in nfs, ceph, 9p and other network filesystems. It is not supported in fuse, although there is a separate patch to enable it. 

One method of implementating a userspace filesystem is use a local server for a network filesystem protocol. The 9p filesystem is particularly suitable for this and about as easy as writing a fuse driver. As a bonus, you get local caching support “for free”.

**Comment by fangfufu** [comment]
Does kernel's generic mechanism for local caching support saving the file for offline use though?

**Comment by fangfufu** [comment]
Release 1.1.0-alpha resolves this issue.
